// +build !ignore_autogenerated

// Code generated by openapi-gen. DO NOT EDIT.

// This file was autogenerated by openapi-gen. Do not edit it manually!

package v1alpha1

import (
	spec "github.com/go-openapi/spec"
	common "k8s.io/kube-openapi/pkg/common"
)

func GetOpenAPIDefinitions(ref common.ReferenceCallback) map[string]common.OpenAPIDefinition {
	return map[string]common.OpenAPIDefinition{
		"github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSource":       schema_pkg_apis_devconsole_operator_v1alpha1_GitSource(ref),
		"github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSourceSpec":   schema_pkg_apis_devconsole_operator_v1alpha1_GitSourceSpec(ref),
		"github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSourceStatus": schema_pkg_apis_devconsole_operator_v1alpha1_GitSourceStatus(ref),
	}
}

func schema_pkg_apis_devconsole_operator_v1alpha1_GitSource(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GitSource is the Schema for the gitsources API",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"kind": {
						SchemaProps: spec.SchemaProps{
							Description: "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"apiVersion": {
						SchemaProps: spec.SchemaProps{
							Description: "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"metadata": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"),
						},
					},
					"spec": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSourceSpec"),
						},
					},
					"status": {
						SchemaProps: spec.SchemaProps{
							Ref: ref("github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSourceStatus"),
						},
					},
				},
			},
		},
		Dependencies: []string{
			"github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSourceSpec", "github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.GitSourceStatus", "k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta"},
	}
}

func schema_pkg_apis_devconsole_operator_v1alpha1_GitSourceSpec(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GitSourceSpec defines the desired state of GitSource",
				Type:        []string{"object"},
				Properties: map[string]spec.Schema{
					"url": {
						SchemaProps: spec.SchemaProps{
							Description: "URL of the git repo",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"ref": {
						SchemaProps: spec.SchemaProps{
							Description: "Ref is a git reference. Optional. \"master\" is used by default.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"contextDir": {
						SchemaProps: spec.SchemaProps{
							Description: "ContextDir is a path to subfolder in the repo. Optional.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"httpProxy": {
						SchemaProps: spec.SchemaProps{
							Description: "HttpProxy is optional.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"httpsProxy": {
						SchemaProps: spec.SchemaProps{
							Description: "HttpsProxy is optional.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"noProxy": {
						SchemaProps: spec.SchemaProps{
							Description: "NoProxy can be used to specify domains for which no proxying should be performed. Optional.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
					"secretRef": {
						SchemaProps: spec.SchemaProps{
							Description: "SecretRef refers to the secret that contains credentials to access the git repo. Optional.",
							Ref:         ref("github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.SecretRef"),
						},
					},
					"flavor": {
						SchemaProps: spec.SchemaProps{
							Description: "Flavor of the git provider like github, gitlab, bitbucket, generic, etc. Optional.",
							Type:        []string{"string"},
							Format:      "",
						},
					},
				},
				Required: []string{"url"},
			},
		},
		Dependencies: []string{
			"github.com/redhat-developer/devconsole-operator/pkg/apis/devconsole-operator/v1alpha1.SecretRef"},
	}
}

func schema_pkg_apis_devconsole_operator_v1alpha1_GitSourceStatus(ref common.ReferenceCallback) common.OpenAPIDefinition {
	return common.OpenAPIDefinition{
		Schema: spec.Schema{
			SchemaProps: spec.SchemaProps{
				Description: "GitSourceStatus defines the observed state of GitSource",
				Type:        []string{"object"},
			},
		},
	}
}
