# TODO: change this to a sane base image
FROM quay.io/openshiftio/toolchain-operator:faab15e

ENV INSTALL_PREFIX=/usr/local/devconsole-operator

COPY bin/devconsole-operator ${INSTALL_PREFIX}/bin/devconsole-operator
RUN echo chmod +x ${INSTALL_PREFIX}/bin/devconsole-operator
