FROM quay.io/openshift/origin-operator-registry:latest

ARG image=quay.io/redhat-developer/devconsole-operator
ARG version=0.1.0
COPY manifests manifests
RUN sed -e "s,REPLACE_IMAGE,${image}," -i manifests/devconsole/${version}/devconsole-operator.v${version}.clusterserviceversion.yaml

RUN initializer
CMD ["registry-server", "--termination-log=log.txt"]
