apiVersion: devconsole.openshift.io/v1alpha1
kind: Component
metadata:
  name: myapp
spec:
  buildType: "nodejs"
  codebase: "https://github.com/sclorg/nodejs-ex" #"https://github.com/nodeshift-starters/nodejs-rest-http-crud"
  port: 8080
  exposed: true

